#!/usr/bin/env bash
set -eufo pipefail
cd "$(dirname "$0")"

if [[ ! -d venv ]]; then
    python3 -m venv --copies --upgrade-deps venv
    ./venv/bin/pip3 install -r requirements.txt
fi

exec ./venv/bin/python3 run.py "$@"
